### ISSUE TITLE
examples can not be executed

### ISSUE THREAD

**Issue by ksrust** [ClickoTON-Foundation/tonconnect#3]
Reproduce:
$ python3 examples/address.py
Universal connect url for Tonkeeper: https://app.tonkeeper.com/ton-connect?v=2&id=ab3bcb764ac889725c15cb65f95ba0665f2bdf8bb2852f3d74f1413803364822&r=%7B%22manifestUrl%22%3A%22https%3A//tonclick.online/ton-connect.json%22%2C%22items%22%3A%5B%7B%22name%22%3A%22ton_addr%22%7D%2C%7B%22name%22%3A%22ton_proof%22%2C%22payload%22%3A%22test%22%7D%5D%7D
Traceback (most recent call last):
  File "/home/rustdev/tonconnect/examples/address.py", line 9, in <module>
    address = connector.get_address()
  File "/home/rustdev/.local/lib/python3.10/site-packages/tonconnect/connector.py", line 84, in get_address
    return asyncio.run(self.async_connector.get_address())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/rustdev/.local/lib/python3.10/site-packages/tonconnect/connector.py", line 43, in get_address
    return await self.check_address_proof_event(event)
  File "/home/rustdev/.local/lib/python3.10/site-packages/tonconnect/connector.py", line 62, in check_address_proof_event
    if event.address is None or event.proof is None:
AttributeError: 'ConnectErrorEvent' object has no attribute 'address'

I tried to open the url generated, but an error occurs.

**Comment by exaho** [comment]
same here, did you fixed?

**Comment by denzyve** [comment]
change the url to for example https://raw.githubusercontent.com/XaBbl4/pytonconnect/main/pytonconnect-manifest.json
